# Generated by Django 3.1.3 on 2020-12-02 14:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_aboutview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.IntegerField()),
                ('description', models.TextField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='AboutView',
        ),
    ]
