# Generated by Django 3.1.3 on 2020-11-15 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_ref_number', models.CharField(default='IRN-100000', max_length=15, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('label', models.CharField(choices=[('Sale', 'Sale'), ('New', 'New'), ('Trending', 'Trending'), ('Top Selling', 'Top Selling'), ('Popular', 'Popular')], max_length=11, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('stock_no', models.IntegerField()),
                ('short_description', models.TextField(help_text='To describe product in short', null=True)),
                ('description', models.TextField(help_text='Overview product', null=True)),
                ('image_main', models.ImageField(null=True, upload_to='')),
                ('image_2', models.ImageField(null=True, upload_to='')),
                ('image_3', models.ImageField(null=True, upload_to='')),
                ('image_4', models.ImageField(null=True, upload_to='')),
                ('image_5', models.ImageField(null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('trending', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category')),
            ],
            options={
                'ordering': ['item_ref_number'],
            },
        ),
    ]
