# Generated by Django 3.1.3 on 2020-11-17 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0002_auto_20201116_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=300)),
                ('review_description', models.TextField()),
                ('rating', models.CharField(choices=[('1', 'Terrible'), ('2', 'Poor'), ('3', 'Average'), ('4', 'Very Good'), ('5', 'Excellent')], max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.ManyToManyField(to='products.Review'),
        ),
    ]
