# Generated by Django 3.1.3 on 2020-12-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20201210_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='model',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
