# Generated by Django 3.1.3 on 2020-11-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20201117_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
        migrations.RemoveField(
            model_name='product',
            name='item_ref_number',
        ),
        migrations.RemoveField(
            model_name='product',
            name='review',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
